#!/usr/bin/env python3
"""Static sanity check for this Homey app (no Node.js / Homey CLI required).

Checks:
  * every .json file in the app parses as valid JSON
  * the required manifest and code files exist
  * the app images and driver images exist and have the required dimensions
  * image paths referenced in the compose files actually resolve

Usage:
    python tools/check_app.py
"""

from __future__ import annotations

import json
import os
import struct
import sys

APP_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REQUIRED_FILES = [
    "app.js",
    "package.json",
    ".homeycompose/app.json",
    "assets/icon.svg",
    "lib/marstek.js",
    "drivers/venus_a/driver.compose.json",
    "drivers/venus_a/driver.flow.compose.json",
    "drivers/venus_a/driver.js",
    "drivers/venus_a/device.js",
    "drivers/venus_a/assets/icon.svg",
    ".homeycompose/flow/actions/set_mode.json",
    ".homeycompose/flow/conditions/mode_is.json",
]

EXPECTED_IMAGES = {
    "assets/images/small.png": (250, 250),
    "assets/images/large.png": (500, 500),
    "assets/images/xlarge.png": (1000, 1000),
    "drivers/venus_a/assets/images/small.png": (75, 75),
    "drivers/venus_a/assets/images/large.png": (500, 500),
    "drivers/venus_a/assets/images/xlarge.png": (1000, 1000),
}

SKIP_DIRS = {"node_modules", ".git", ".homeybuild"}

errors: list[str] = []
warnings: list[str] = []


def full(relative_path: str) -> str:
    return os.path.join(APP_ROOT, *relative_path.split("/"))


def read_png_size(path: str):
    with open(path, "rb") as handle:
        header = handle.read(24)
    if header[:8] != b"\x89PNG\r\n\x1a\n" or header[12:16] != b"IHDR":
        return None
    width, height = struct.unpack(">II", header[16:24])
    return width, height


def check_json_files() -> None:
    count = 0
    for current_root, dirs, files in os.walk(APP_ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in files:
            if not name.endswith(".json"):
                continue
            path = os.path.join(current_root, name)
            relative = os.path.relpath(path, APP_ROOT).replace("\\", "/")
            if relative == "app.json":
                continue  # generated by the Homey CLI
            count += 1
            try:
                with open(path, "r", encoding="utf-8") as handle:
                    json.load(handle)
            except Exception as exc:  # noqa: BLE001
                errors.append(f"ongeldige JSON in {relative}: {exc}")
    print(f"JSON-bestanden gecontroleerd: {count}")


def check_required_files() -> None:
    for relative in REQUIRED_FILES:
        if not os.path.isfile(full(relative)):
            errors.append(f"ontbrekend bestand: {relative}")


def check_images() -> None:
    for relative, expected in EXPECTED_IMAGES.items():
        path = full(relative)
        if not os.path.isfile(path):
            errors.append(f"ontbrekende afbeelding: {relative}")
            continue
        size = read_png_size(path)
        if size is None:
            errors.append(f"geen geldige PNG: {relative}")
            continue
        if size != expected:
            errors.append(
                f"verkeerde afmeting voor {relative}: {size[0]}x{size[1]}, "
                f"verwacht {expected[0]}x{expected[1]}"
            )


def check_compose_image_paths() -> None:
    compose_files = [
        ".homeycompose/app.json",
        "drivers/venus_a/driver.compose.json",
    ]
    for relative in compose_files:
        path = full(relative)
        if not os.path.isfile(path):
            continue
        with open(path, "r", encoding="utf-8") as handle:
            manifest = json.load(handle)

        for key, value in (manifest.get("images") or {}).items():
            if not isinstance(value, str):
                continue
            target = value.lstrip("/")
            if not os.path.isfile(full(target)):
                errors.append(f"{relative}: afbeelding '{key}' verwijst naar ontbrekend bestand {value}")


def check_flow_cards() -> None:
    """Make sure every flow card referenced from JavaScript exists on disk.

    App-level compose cards derive their id from the file name, driver level
    cards declare an explicit "id" field.
    """
    app_level = {
        ".homeycompose/flow/actions/set_mode.json": "set_mode",
        ".homeycompose/flow/conditions/mode_is.json": "mode_is",
    }
    for relative, card_id in app_level.items():
        path = full(relative)
        if not os.path.isfile(path):
            continue
        if os.path.splitext(os.path.basename(relative))[0] != card_id:
            errors.append(f"{relative}: bestandsnaam komt niet overeen met kaart-id '{card_id}'")
        with open(path, "r", encoding="utf-8") as handle:
            card = json.load(handle)
        if "title" not in card:
            errors.append(f"{relative}: flow-kaart '{card_id}' mist een 'title'")
        if "args" not in card:
            errors.append(f"{relative}: flow-kaart '{card_id}' mist 'args'")

    driver_cards = full("drivers/venus_a/driver.flow.compose.json")
    with open(driver_cards, "r", encoding="utf-8") as handle:
        cards = json.load(handle)
    trigger_ids = [card.get("id") for card in cards.get("triggers") or []]
    if "mode_changed" not in trigger_ids:
        errors.append("driver.flow.compose.json: trigger 'mode_changed' ontbreekt")

    device_js = full("drivers/venus_a/device.js")
    with open(device_js, "r", encoding="utf-8") as handle:
        device_source = handle.read()
    if "getDeviceTriggerCard('mode_changed')" not in device_source:
        warnings.append("device.js registreert de trigger mode_changed niet zoals verwacht")


def check_capabilities() -> None:
    with open(full("drivers/venus_a/driver.compose.json"), "r", encoding="utf-8") as handle:
        manifest = json.load(handle)

    capabilities = manifest.get("capabilities") or []
    for capability in ("onoff",):
        if capability not in capabilities:
            errors.append(f"driver venus_a mist de capaciteit '{capability}'")

    setting_ids = set()
    for group in manifest.get("settings") or []:
        for child in group.get("children") or []:
            if child.get("id"):
                setting_ids.add(child["id"])

    with open(full("drivers/venus_a/device.js"), "r", encoding="utf-8") as handle:
        source = handle.read()

    for used in ("host", "port", "poll_interval", "mode_on", "mode_off", "manual_power"):
        if used not in setting_ids:
            errors.append(f"instelling '{used}' wordt in device.js gebruikt maar staat niet in driver.compose.json")
        elif f"settings.{used}" not in source and f"'{used}'" not in source:
            warnings.append(f"instelling '{used}' wordt niet in device.js gebruikt")


def check_javascript_balance() -> None:
    """Light sanity check on the .js files (Node.js is not always installed).

    Verifies that braces, brackets and parentheses balance, while ignoring
    string literals and comments.
    """
    pairs = {")": "(", "]": "[", "}": "{"}

    for current_root, dirs, files in os.walk(APP_ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in files:
            if not name.endswith(".js"):
                continue

            path = os.path.join(current_root, name)
            relative = os.path.relpath(path, APP_ROOT).replace("\\", "/")
            with open(path, "r", encoding="utf-8") as handle:
                source = handle.read()

            stack = []
            index = 0
            line = 1
            length = len(source)

            while index < length:
                char = source[index]

                if char == "\n":
                    line += 1
                    index += 1
                    continue

                if char == "/" and index + 1 < length and source[index + 1] == "/":
                    while index < length and source[index] != "\n":
                        index += 1
                    continue

                if char == "/" and index + 1 < length and source[index + 1] == "*":
                    index += 2
                    while index + 1 < length and not (source[index] == "*" and source[index + 1] == "/"):
                        if source[index] == "\n":
                            line += 1
                        index += 1
                    index += 2
                    continue

                if char in ('"', "'", "`"):
                    quote = char
                    index += 1
                    while index < length:
                        if source[index] == "\\":
                            index += 2
                            continue
                        if source[index] == quote:
                            index += 1
                            break
                        if source[index] == "\n":
                            line += 1
                        index += 1
                    continue

                if char in "([{":
                    stack.append((char, line))
                elif char in ")]}":
                    if not stack or stack[-1][0] != pairs[char]:
                        errors.append(f"{relative}:{line}: onverwachte '{char}'")
                    else:
                        stack.pop()

                index += 1

            if stack:
                errors.append(
                    f"{relative}: '{stack[-1][0]}' geopend op regel {stack[-1][1]} wordt niet gesloten"
                )


def main() -> int:
    check_json_files()
    check_javascript_balance()
    check_required_files()
    check_images()
    check_compose_image_paths()
    check_flow_cards()
    check_capabilities()

    for warning in warnings:
        print(f"WAARSCHUWING: {warning}")
    for error in errors:
        print(f"FOUT: {error}")

    if errors:
        print(f"\n{len(errors)} probleem(en) gevonden.")
        return 1

    print("\nAlles in orde.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
